#!/usr/bin/env bash

# Setup bdtgreen database with user datatrans

# Create datatrans user if it does not already exist
if [[ -z $(docker exec backend gosu postgres psql postgres -tAc \
"SELECT 1 FROM pg_roles WHERE rolname='datatrans'") ]]; then
    docker exec backend gosu postgres psql -c "CREATE USER datatrans WITH PASSWORD 'somepassword';";
else
    echo "User datatrans already exists";
fi

# Create bdtgreen database if it does not already exist
if [[ -z $(docker exec backend gosu postgres psql postgres -tAc \
"SELECT 1 from pg_database WHERE datname='bdtgreen'") ]]; then
    docker exec backend gosu postgres psql -c "CREATE DATABASE bdtgreen;";
else
    echo "Database bdtgreen already exists";
fi

# Grant all privileges on bdtgreen to datatrans if not already applied
docker exec backend gosu postgres psql -c 'GRANT ALL PRIVILEGES ON DATABASE "bdtgreen" TO datatrans;'

# Create extension postgis, postgis_topology and ogr_fdw
#                                         List of installed extensions
#       Name       | Version |   Schema   |                             Description
#------------------+---------+------------+---------------------------------------------------------------------
# ogr_fdw          | 1.0     | public     | foreign-data wrapper for GIS data access
# plpgsql          | 1.0     | pg_catalog | PL/pgSQL procedural language
# postgis          | 2.2.5   | public     | PostGIS geometry, geography, and raster spatial types and functions
# postgis_topology | 2.2.5   | topology   | PostGIS topology spatial types and functions
if [[ -z $(docker exec backend gosu postgres psql bdtgreen -tAc \
"SELECT 1 from pg_extension WHERE extname='postgis'") ]]; then
    docker exec backend gosu postgres psql bdtgreen -c "CREATE EXTENSION postgis;";
else
    echo "Extension postgis already exists";
fi
if [[ -z $(docker exec backend gosu postgres psql bdtgreen -tAc \
"SELECT 1 from pg_extension WHERE extname='postgis_topology'") ]]; then
    docker exec backend gosu postgres psql bdtgreen -c "CREATE EXTENSION postgis_topology;";
else
    echo "Extension postgis_topology already exists";
fi
if [[ -z $(docker exec backend gosu postgres psql bdtgreen -tAc \
"SELECT 1 from pg_extension WHERE extname='ogr_fdw'") ]]; then
    docker exec backend gosu postgres psql bdtgreen -c "CREATE EXTENSION ogr_fdw;";
else
    echo "Extension ogr_fdw already exists";
fi

exit 0;