#!/usr/bin/env bash

LOCAL_HOME=$(pwd)

# purge prior backend
./dbctl purge

# Launch database backend
./dbctl start
sleep 10s

# Setup database bdtgreen and user datatrans
cd ${LOCAL_HOME}/sample-data/
./setup-bdtgreen

# Load Cmaq data
cd ${LOCAL_HOME}/sample-data/cmaq/
./load-cmaq-sample

# Load ExposureType data
cd ${LOCAL_HOME}/sample-data/exposure_types/
./load-exposure-type

# Setup api server
cd ${LOCAL_HOME}/python-flask-server/
./run-in-docker "$@"

exit 0;